on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build --build-arg extra='npm test' -t rest-api-lint .
